export type MockOutlierPost = {
  id: string;
  creatorName: string;
  handle: string;
  platform: string;
  postedAgo: string;
  preview: string;
  likes: string;
  comments: string;
  views: string;
  outlierMultiple: string;
  hasThumbnail?: boolean;
  thumbnailTone?: "slate" | "warm" | "cool";
  thumbnailHeight?: "short" | "tall";
  captionBelowThumbnail?: string;
};

/** Mock watchlist signals — frontend placeholder only. */
export const MOCK_OUTLIER_POSTS: MockOutlierPost[] = [
  {
    id: "outlier-1",
    creatorName: "Lenny Rachitsky",
    handle: "@lennysan",
    platform: "X",
    postedAgo: "1mo",
    preview:
      "The best product advice I got this year: ship the uncomfortable version first. Everything else is rehearsal.",
    likes: "2.1K",
    comments: "164",
    views: "368K",
    outlierMultiple: "11x",
    hasThumbnail: true,
    thumbnailTone: "warm",
    thumbnailHeight: "tall",
    captionBelowThumbnail: "Why uncomfortable launches beat polished delays",
  },
  {
    id: "outlier-2",
    creatorName: "Sahil Bloom",
    handle: "@SahilBloom",
    platform: "X",
    postedAgo: "3w",
    preview: "A simple framework for deciding what to work on next quarter.",
    likes: "1.4K",
    comments: "92",
    views: "210K",
    outlierMultiple: "4.2x",
  },
  {
    id: "outlier-3",
    creatorName: "Ali Abdaal",
    handle: "@AliAbdaal",
    platform: "YouTube",
    postedAgo: "2w",
    preview: "How I structure long-form videos when the topic is abstract.",
    likes: "8.9K",
    comments: "412",
    views: "1.2M",
    outlierMultiple: "27x",
    hasThumbnail: true,
    thumbnailTone: "cool",
    thumbnailHeight: "short",
  },
  {
    id: "outlier-4",
    creatorName: "Morgan Housel",
    handle: "@morganhousel",
    platform: "Newsletter",
    postedAgo: "5d",
    preview:
      "Most financial mistakes are not math errors. They are temperament errors dressed up as spreadsheets.",
    likes: "3.6K",
    comments: "201",
    views: "540K",
    outlierMultiple: "8.1x",
  },
  {
    id: "outlier-5",
    creatorName: "Anne-Laure Le Cunff",
    handle: "@anthilemoon",
    platform: "X",
    postedAgo: "1w",
    preview: "Notes on building a writing practice without waiting for inspiration.",
    likes: "980",
    comments: "74",
    views: "142K",
    outlierMultiple: "5.6x",
    hasThumbnail: true,
    thumbnailTone: "slate",
    thumbnailHeight: "short",
  },
  {
    id: "outlier-6",
    creatorName: "David Perell",
    handle: "@david_perell",
    platform: "Podcast",
    postedAgo: "4d",
    preview: "Three questions I ask before publishing anything ambitious.",
    likes: "1.1K",
    comments: "58",
    views: "96K",
    outlierMultiple: "3.8x",
  },
  {
    id: "outlier-7",
    creatorName: "Nat Eliason",
    handle: "@nateliason",
    platform: "X",
    postedAgo: "2d",
    preview:
      "The creator economy mistake: optimizing for reach before you have a point of view worth repeating.",
    likes: "2.8K",
    comments: "133",
    views: "401K",
    outlierMultiple: "15x",
    hasThumbnail: true,
    thumbnailTone: "warm",
    thumbnailHeight: "tall",
    captionBelowThumbnail: "Reach without a thesis is just noise with better distribution",
  },
  {
    id: "outlier-8",
    creatorName: "Julie Zhuo",
    handle: "@joulee",
    platform: "LinkedIn",
    postedAgo: "6d",
    preview: "What changed in how I give feedback after ten years of management.",
    likes: "1.9K",
    comments: "87",
    views: "178K",
    outlierMultiple: "6.4x",
  },
  {
    id: "outlier-9",
    creatorName: "Tim Ferriss",
    handle: "@tferriss",
    platform: "Reel",
    postedAgo: "3d",
    preview: "A 60-second clip on saying no without burning bridges.",
    likes: "4.2K",
    comments: "219",
    views: "620K",
    outlierMultiple: "33x",
    hasThumbnail: true,
    thumbnailTone: "cool",
    thumbnailHeight: "tall",
  },
  {
    id: "outlier-10",
    creatorName: "James Clear",
    handle: "@JamesClear",
    platform: "X",
    postedAgo: "1w",
    preview: "Small habits compound when the environment stops fighting you.",
    likes: "5.1K",
    comments: "302",
    views: "890K",
    outlierMultiple: "9.3x",
  },
  {
    id: "outlier-11",
    creatorName: "Visakan Veerasamy",
    handle: "@visakanv",
    platform: "X",
    postedAgo: "2w",
    preview: "Thread outline: how to write online without performing expertise you do not have.",
    likes: "760",
    comments: "49",
    views: "118K",
    outlierMultiple: "4.9x",
  },
  {
    id: "outlier-12",
    creatorName: "Elena Verna",
    handle: "@ElenaVerna",
    platform: "X",
    postedAgo: "5d",
    preview: "PLG only works when the product teaches users why they should stay.",
    likes: "1.3K",
    comments: "96",
    views: "233K",
    outlierMultiple: "7.2x",
    hasThumbnail: true,
    thumbnailTone: "slate",
    thumbnailHeight: "short",
  },
  {
    id: "outlier-13",
    creatorName: "Patrick Collison",
    handle: "@patrickc",
    platform: "X",
    postedAgo: "3w",
    preview: "A reading list disguised as a tweet. Books that changed how I think about institutions.",
    likes: "3.2K",
    comments: "188",
    views: "512K",
    outlierMultiple: "12x",
  },
  {
    id: "outlier-14",
    creatorName: "Swyx",
    handle: "@swyx",
    platform: "Newsletter",
    postedAgo: "4d",
    preview: "Learning in public works when the audience can see your thinking, not just your wins.",
    likes: "890",
    comments: "61",
    views: "104K",
    outlierMultiple: "3.1x",
  },
];
